package com.mattmx.datapack.objects

class McMetaFile(val id: String) {
    val pack = PackData()
}

data class PackData(
    var description: String = "This datapack was generated by DPTranslator!",
    var pack_format: Int = 10
)